# Generated by Django 4.0.4 on 2022-12-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitmens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
