# Generated by Django 4.0.4 on 2022-12-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitmens', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitmen',
            name='title',
            field=models.CharField(choices=[('MANAGER', 'MANAGER'), ('HITMEN', 'HITMEN')], max_length=50),
        ),
    ]
