# Generated by Django 4.0.4 on 2022-12-14 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitmens', '0004_alter_hitmen_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitmen',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hitmen',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 7, 18, 1, 787928)),
        ),
    ]
