version: "3"

services:

  db:
    image: postgres:12-alpine3.15
    container_name: db-spy
    env_file: .env
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build:
      context: .
    env_file: .env
    command: sh -c "python3 manage.py migrate && python3 manage.py loaddata inital_data.json &&
      python3 manage.py runserver 0.0.0.0:8000"
    ports:
        - "8000:8000"
    volumes:
        - .:/app
    restart: always
    depends_on:
      - db
