# Generated by Django 4.0.4 on 2022-12-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hitmens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
                ('status', models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('COMPLETED', 'COMPLETED'), ('FAILED_ASSIGNED', 'FAILED_ASSIGNED')], default='ASSIGNED', max_length=200)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hits', to='hitmens.hitmen')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hitmens.hitmen')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
