# Generated by Django 4.0.4 on 2022-12-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0002_alter_hit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='status_hitmen',
            field=models.CharField(choices=[('ASSIGNED', 'ASSIGNED'), ('COMPLETED', 'COMPLETED'), ('FAILED_ASSIGNED', 'FAILED_ASSIGNED'), ('FAILED', 'FAILED')], default='ASSIGNED', max_length=200),
        ),
        migrations.AlterField(
            model_name='hit',
            name='status',
            field=models.CharField(choices=[('CLOSED', 'CLOSED'), ('OPEN', 'OPEN'), ('FAILED', 'FAILED')], default='OPEN', max_length=200),
        ),
    ]
