# Generated by Django 4.0.4 on 2022-12-14 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hits', '0006_alter_hit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 14, 7, 20, 54, 653747)),
        ),
    ]
